# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20180621_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hash_password',
            new_name='password',
        ),
    ]
