# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-23 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_cmt', to='login_registration.Message'),
            preserve_default=False,
        ),
    ]
